name: AI-Team CI (label-gated)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  ai_team_ci:
    if: contains(github.event.pull_request.labels.*.name, 'ai-team')
    runs-on:
      group: TestRunners

    steps:
      - name: Banner
        run: echo "AI-Team CI lane running (ai-team label present)"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Detect Node project
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f package.json ]; then
            echo "has_package_json=false" >> "$GITHUB_OUTPUT"
            echo "No package.json at repo root; skipping Node lint/test/build."
            exit 0
          fi
          echo "has_package_json=true" >> "$GITHUB_OUTPUT"
          if [ -f pnpm-lock.yaml ]; then
            echo "pm=pnpm" >> "$GITHUB_OUTPUT"
          elif [ -f yarn.lock ]; then
            echo "pm=yarn" >> "$GITHUB_OUTPUT"
          else
            echo "pm=npm" >> "$GITHUB_OUTPUT"
          fi

      - name: Install dependencies (pnpm)
        if: steps.detect.outputs.has_package_json == 'true' && steps.detect.outputs.pm == 'pnpm'
        shell: bash
        run: |
          set -euo pipefail
          corepack enable
          pnpm --version
          pnpm install --frozen-lockfile

      - name: Install dependencies (yarn)
        if: steps.detect.outputs.has_package_json == 'true' && steps.detect.outputs.pm == 'yarn'
        shell: bash
        run: |
          set -euo pipefail
          corepack enable
          yarn --version
          yarn install --frozen-lockfile

      - name: Install dependencies (npm)
        if: steps.detect.outputs.has_package_json == 'true' && steps.detect.outputs.pm == 'npm'
        shell: bash
        run: |
          set -euo pipefail
          npm ci

      - name: Lint (if script exists)
        if: steps.detect.outputs.has_package_json == 'true'
        shell: bash
        run: |
          set -euo pipefail
          PM="${{ steps.detect.outputs.pm }}"
          if node -e "const p=require('./package.json'); process.exit(p?.scripts?.lint?0:1)"; then
            if [ "$PM" = "pnpm" ]; then pnpm run lint;
            elif [ "$PM" = "yarn" ]; then yarn run lint;
            else npm run lint; fi
          else
            echo "No scripts.lint; skipping."
          fi

      - name: Test (if script exists)
        if: steps.detect.outputs.has_package_json == 'true'
        shell: bash
        run: |
          set -euo pipefail
          PM="${{ steps.detect.outputs.pm }}"
          if node -e "const p=require('./package.json'); process.exit(p?.scripts?.test?0:1)"; then
            if [ "$PM" = "pnpm" ]; then pnpm test;
            elif [ "$PM" = "yarn" ]; then yarn test;
            else npm test; fi
          else
            echo "No scripts.test; skipping."
          fi

      - name: Build (if script exists)
        if: steps.detect.outputs.has_package_json == 'true'
        shell: bash
        run: |
          set -euo pipefail
          PM="${{ steps.detect.outputs.pm }}"
          if node -e "const p=require('./package.json'); process.exit(p?.scripts?.build?0:1)"; then
            if [ "$PM" = "pnpm" ]; then pnpm run build;
            elif [ "$PM" = "yarn" ]; then yarn run build;
            else npm run build; fi
          else
            echo "No scripts.build; skipping."
          fi
